// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { PlanType } from "../PlanType";

/**
 * Metadata for one locally named credential record. Credential material is never included.
 */
export type NamedAccount = { id: string, label: string, isActive: boolean, accountId: string | null, email: string | null, authMode: AuthMode, planType: PlanType | null, };
