// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * Resolved model selection recorded with sub-agent activity.
 */
export type SubAgentRouting = { model: string, reasoningEffort: ReasoningEffort | null, };
