// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadTasksReadResponse = {
/**
 * Human-readable snapshot of every unfinished task with its complete details.
 * Completed and cancelled task rows are excluded.
 */
text: string, };
