// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadCwdSetParams = { threadId: string,
/**
 * Absolute working directory to load for this idle local thread.
 * Reloads workspace configuration while retaining the thread's identity and history.
 */
cwd: string,
/**
 * Client-provided developer instructions for the destination workspace.
 * When omitted, use the instructions from the reloaded configuration.
 */
developerInstructions?: string | null, };
