// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown,
/**
 * Effective automatic-compaction budget used, rounded up and capped at 100 percent.
 */
autoCompactPercentUsed: number | null, modelContextWindow: number | null, };
