// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadTaskParallelismParams = { threadId: string,
/**
 * Set this session's task capacity immediately. Omit or use null to read it.
 * Zero disables capacity limits and completion reminders.
 */
parallelism?: number | null, };
